calibration:
  alpha: 0.5
  camera_types:
    - GP1
    - GP2
    - SONY_70
    - SONY_300
  directories:
    base: data/SD_01_SURF_FOOTAGE_SOURCE
    parameters: 01_CALIBRATION/parameters
  use_calibrated_footage: false
directories:
  output:
    base: data/SD_02_SURF_FOOTAGE_PREPT
    clips: 03_CLIPPED
    configs: _configs
  proxy:
    base: proxy_videos
    clipped: CLIPPED
    raw: RAW
  source:
    base: data/SD_01_SURF_FOOTAGE_SOURCE
    calibrated: 01_CALIBRATION
    raw: 00_RAW
export:
  create_missing_dirs: true
  preserve_structure: true
  crop_variations:
    enabled: true
    camera_types:
      - SONY_300
      - SONY_70
patterns:
  video_extensions:
    - .mp4
    - .avi
    - .mov
    - .mkv
proxy:
  audio_bitrate: 128k
  enabled: true
  quality: 28
  width: 950
