# Directory structure configuration
directories:
  # Source footage location
  source:
    base: "data/source"
    calibrated: "02_CALIBRATED_FOOTAGE" # Relative to source base

  # Output and configuration locations
  output:
    base: "data/prept"
    clips: "03_CLIPPED" # Relative to output base
    configs: "_configs" # Relative to clips directory

  # Proxy videos location
  proxy:
    base: "proxy_videos" # Directory for proxy videos (relative to project root)

# File patterns
patterns:
  video_extensions: [".mp4", ".avi", ".mov", ".mkv"]

# Export settings
export:
  preserve_structure: true # Preserve session/camera folder structure when exporting
  create_missing_dirs: true # Create directories if they don't exist

# Proxy video settings
proxy:
  enabled: true # Whether to create proxy videos
  width: 960 # Width of proxy videos (height will be calculated to maintain aspect ratio)
  quality: 28 # CRF value for proxy videos (lower is better quality, higher is smaller file)
  audio_bitrate: "128k" # Audio bitrate for proxy videos
