directories:
  output:
    base: data/prept
    clips: 03_CLIPPED
    configs: _configs
  proxy:
    base: proxy_videos
    clipped: CLIPPED
    raw: RAW
  source:
    base: data/source
    calibrated: 02_CALIBRATED_FOOTAGE
export:
  create_missing_dirs: true
  preserve_structure: true
patterns:
  video_extensions:
  - .mp4
  - .avi
  - .mov
  - .mkv
proxy:
  audio_bitrate: 128k
  enabled: true
  quality: 28
  width: 950
